// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBF1MxtkE0mk3prU6_UagWPezD-18-Vx7Y',
    appId: '1:941009135597:web:8f7e783104465ccd8469e4',
    messagingSenderId: '941009135597',
    projectId: 'worktiming-69781',
    authDomain: 'worktiming-69781.firebaseapp.com',
    storageBucket: 'worktiming-69781.appspot.com',
    measurementId: 'G-G5SL14MZMC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0K_6AzkJ2v4RuExybcdHx2tv75vTv6i4',
    appId: '1:941009135597:android:84fe5a25e4b0ae478469e4',
    messagingSenderId: '941009135597',
    projectId: 'worktiming-69781',
    storageBucket: 'worktiming-69781.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGzXpoH5Isn-S1QtsvQhN_othmHxUYgtQ',
    appId: '1:941009135597:ios:9a1eb0cd7f02826a8469e4',
    messagingSenderId: '941009135597',
    projectId: 'worktiming-69781',
    storageBucket: 'worktiming-69781.appspot.com',
    androidClientId: '941009135597-lalacfilhite1262id3km9a1gtfpu3l6.apps.googleusercontent.com',
    iosClientId: '941009135597-rgj76a1tkcv47s0ndedjejdv5bso79cb.apps.googleusercontent.com',
    iosBundleId: 'com.example.worktiming',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGzXpoH5Isn-S1QtsvQhN_othmHxUYgtQ',
    appId: '1:941009135597:ios:b7fb9238605fb4e98469e4',
    messagingSenderId: '941009135597',
    projectId: 'worktiming-69781',
    storageBucket: 'worktiming-69781.appspot.com',
    androidClientId: '941009135597-lalacfilhite1262id3km9a1gtfpu3l6.apps.googleusercontent.com',
    iosClientId: '941009135597-bq8clc5vvgqel5nr2bcfsf3gri7bd0dh.apps.googleusercontent.com',
    iosBundleId: 'com.example.worktiming.RunnerTests',
  );
}
